"""create scheme eligibility rule table

Revision ID: 241beca932b6
Revises: e23e807401f2
Create Date: 2026-09-04 16:19:36.208442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241beca932b6'
down_revision: Union[str, Sequence[str], None] = 'e23e807401f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_eligibility_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('minimum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_age', sa.Integer(), nullable=True),
    sa.Column('maximum_annual_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('required_district', sa.String(length=100), nullable=True),
    sa.Column('required_occupation', sa.String(length=100), nullable=True),
     sa.CheckConstraint(
        'maximum_annual_income IS NULL OR maximum_annual_income >= 0',
        name='ck_eligibility_income_non_negative',
    ),
    sa.CheckConstraint(
        'maximum_age IS NULL OR maximum_age >= 0',
        name='ck_eligibility_maximum_age_non_negative',
    ),
    sa.CheckConstraint(
        'minimum_age IS NULL OR maximum_age IS NULL OR minimum_age <= maximum_age',
        name='ck_eligibility_age_range',
    ),
    sa.CheckConstraint(
        'minimum_age IS NULL OR minimum_age >= 0',
        name='ck_eligibility_minimum_age_non_negative',
    ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_eligibility_rule_scheme_id'), 'scheme_eligibility_rule', ['scheme_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_eligibility_rule_scheme_id'), table_name='scheme_eligibility_rule')
    op.drop_table('scheme_eligibility_rule')
    # ### end Alembic commands ###
