"""create scheme application table

Revision ID: 27f138e6682c
Revises: 241beca932b6
Create Date: 2026-09-06 11:34:40.391785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f138e6682c'
down_revision: Union[str, Sequence[str], None] = '241beca932b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_scheme_application_valid_status'),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scheme_id', name='uq-scheme_application_user_scheme')
    )
    op.create_index(op.f('ix_scheme_application_scheme_id'), 'scheme_application', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_scheme_application_user_id'), 'scheme_application', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_application_user_id'), table_name='scheme_application')
    op.drop_index(op.f('ix_scheme_application_scheme_id'), table_name='scheme_application')
    op.drop_table('scheme_application')
    # ### end Alembic commands ###
