"""add eligibility to scheme

Revision ID: 9594e167a015
Revises: a10f68fce859
Create Date: 2026-09-02 14:44:17.217232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9594e167a015'
down_revision: Union[str, Sequence[str], None] = 'a10f68fce859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme', sa.Column('eligibility', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheme', 'eligibility')
    # ### end Alembic commands ###
